package com.nhbhuiyan.nestify.ui.theme
import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Schedule Category Colors
val ScheduleWeekly = Color(0xFF3498DB)
val ScheduleMonthly = Color(0xFF9B59B6)
val ScheduleYearly = Color(0xFF27AE60)
val ScheduleBackground = Color(0xFFF8FAFB)
val ScheduleCardSurface = Color(0xFFFFFFFF)
val ScheduleTextPrimary = Color(0xFF2C3E50)
val ScheduleTextSecondary = Color(0xFF7F8C8D)
val ScheduleDivider = Color(0xFFECF0F1)

// Nestify Brand Colors
val NestifyPeach = Color(0xFFE6D0BA)
val NestifyBlueGray = Color(0xFFA8BCC2)
val NestifySkyBlue = Color(0xFFC7DBE3)
val NestifyDeepBlue = Color(0xFFAEC4D1)
val NestifySlate = Color(0xFF333F48)
val NestifyGreen = Color(0xFF7BB87B)
val NestifyWhite = Color(0xFFFFFFFF)
val NestifySurface = Color(0xFFF7F9FB)


val md_theme_light_primary = Color(0xFF4A6572) // Derived from Slate/Blue
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC7DBE3)
val md_theme_light_onPrimaryContainer = Color(0xFF001F29)
val md_theme_light_secondary = Color(0xFF7BB87B)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4EABB)
val md_theme_light_onSecondaryContainer = Color(0xFF102004)
val md_theme_light_tertiary = Color(0xFFE6D0BA)
val md_theme_light_onTertiary = Color(0xFF432C00)
val md_theme_light_tertiaryContainer = Color(0xFFFFDDB3)
val md_theme_light_onTertiaryContainer = Color(0xFF291800)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7F9FB)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFF7F9FB)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EB)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72777F)
val md_theme_light_inverseOnSurface = Color(0xFFF1F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3033)
val md_theme_light_inversePrimary = Color(0xFFAEC4D1)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4A6572)
val md_theme_light_outlineVariant = Color(0xFFC2C7CF)
val md_theme_light_scrim = Color(0xFF000000)


val md_theme_dark_primary = Color(0xFFAEC4D1)
val md_theme_dark_onPrimary = Color(0xFF003544)
val md_theme_dark_primaryContainer = Color(0xFF004D62)
val md_theme_dark_onPrimaryContainer = Color(0xFFC7DBE3)
val md_theme_dark_secondary = Color(0xFFB8CEA1)
val md_theme_dark_onSecondary = Color(0xFF243515)
val md_theme_dark_secondaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4EABB)
val md_theme_dark_tertiary = Color(0xFFE6D0BA)
val md_theme_dark_onTertiary = Color(0xFF432C00)
val md_theme_dark_tertiaryContainer = Color(0xFF614000)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDDB3)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEAE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CF)
val md_theme_dark_outline = Color(0xFF8C9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF4A6572)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFAEC4D1)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF825500)